### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by XiongAmao** [XiongAmao/vue-easy-lightbox#11]
- [x] Custom toolbar/btns/ options #5 
- [x] Description text #9 
- [x] Rewrite class name
- [ ] New document ( vuePress ?)
- [x] Mobile support #4 
- [x] Minimize bundle size #12
- [x] Provide es5 / es6+ #12 
- [x] Img loading.
- [x] escape pressing
- [x] TypeScript support
- [x] Rewrite to TypeScript
- [x] Minize TypeScript build size (with babel)
- [ ] Customize Styles support
- [x] Error handler
- [ ] Refactor with tsx
- [x] btn click event & index change event

**Comment by mohyM** [comment]
add callback listener to next and previous button to do function like (load more images from server ) I think it will be very useful

**Comment by XiongAmao** [comment]
Hi, @mohyM 
I add events(`on-prev-click`/`on-next-click`/`on-index-change`) in v0.11.0 .
You can also use [slot](https://github.com/XiongAmao/vue-easy-lightbox#use-vue-slot-custom-buttons-or-toolbar) to customize btn to implement the same feature.

**Comment by mohyM** [comment]
@XiongAmao  please help me how can I use these events(on-prev-click/on-next-click/on-index-change) on a component to do something please help :)

**Comment by XiongAmao** [comment]
@mohyM I made a demo https://github.com/XiongAmao/vue-easy-lightbox/blob/master/demos/event-handler/src/App.vue

**Comment by mohyM** [comment]
@XiongAmao thanks for your efforts but i have another idea to create list of thumbnails of image that preview index of image and all images at bottom of the screen

**Comment by XiongAmao** [comment]
@mohyM I don't plan to develop this feature for now , maybe latter. 
Welcome PR.

**Comment by mohyM** [comment]
@XiongAmao Thanks for your reply, I can help you to implement this feature if you want thanks, bro
