### ISSUE TITLE
TODO 2021

### ISSUE THREAD

**Issue by XiongAmao** [XiongAmao/vue-easy-lightbox#64]
- [x] Prevent scroll chaning
- [x] Refactor to compotion api
- [x] New docs
- [ ] i18n
- [ ] Accessibility
- [ ] Common Options
- [x] Fix docs typo
- [x] Fix Incorrect Demo
- [x] Support for Vue3 tsx event types
- [x] css classname
- [x] Enhance the gesture experience on the mobile device. #63 
- [x] Replace VuePress to VuePress2 or VitePress
